#!/bin/bash

# Set the IP address of the host machine in the play configuration file

echo -e "Please enter the IP address of the host machine:"
read hostIP
echo "morphia.db.seeds=$hostIP:27017" >> conf/application.conf

# Find and display the IP address of VM and display the url to use

vmIP=`ifconfig  eth0 | grep 'inet addr:'| cut -d: -f2 | awk '{ print $1}'`
echo 'Type the following url from host machine browser to access the SensorAct application:'
echo -ne '\t http://'
echo "$vmIP:9003/" 

