#!/bin/bash

#Take a backup of the existing log file
logfile=${SENSORACT_HOME}"logs/system.out"

#Get the command option
arg=$1

if [ "$arg" = 'start' ]; then
	if [ -f $logfile ]; then
		cp $logfile $logfile.`date +%s`
		play start
	else
		play start
	fi
elif [ "$arg" = 'stop' ]; then
	play stop
elif [ "$arg" = 'restart' ]; then
	play stop
	play start
elif [ "$arg" = 'update' ]; then
	play stop
	git pull
	play start
	
else
	echo 'Wrong command. Please type in this format-> sensoract <start|stop|update|restart>'
fi
